/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#efdee9",
        "on-surface": "#221921",
        "secondary-fixed-dim": "#00dbe9",
        "surface": "#fff7fa",
        "primary": "#a900a9",
        "tertiary": "#695f00",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "surface-container-low": "#ffeff9",
        "primary-container": "#ff00ff",
        "tertiary-fixed-dim": "#dbc900",
        "background": "#fff7fa",
        "inverse-primary": "#ffabf3",
        "on-tertiary-container": "#474000",
        "on-secondary-fixed-variant": "#004f54",
        "tertiary-fixed": "#fae500",
        "on-secondary-fixed": "#002022",
        "secondary-container": "#00eefc",
        "surface-container": "#fbe9f5",
        "tertiary-container": "#bdad00",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#564052",
        "on-secondary-container": "#00686f",
        "error": "#ba1a1a",
        "on-primary-fixed": "#380038",
        "secondary-fixed": "#7df4ff",
        "primary-fixed": "#ffd7f5",
        "on-tertiary-fixed": "#1f1c00",
        "surface-container-high": "#f5e3ef",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#4f4800",
        "primary-fixed-dim": "#ffabf3",
        "surface-container-highest": "#efdee9",
        "on-primary-fixed-variant": "#810081",
        "secondary": "#006970",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "outline": "#897083",
        "on-error": "#ffffff",
        "surface-bright": "#fff7fa",
        "on-primary-container": "#510051",
        "outline-variant": "#dcbed4",
        "inverse-surface": "#382d36",
        "on-background": "#221921",
        "surface-tint": "#a900a9",
        "inverse-on-surface": "#feecf8",
        "surface-dim": "#e6d5e1"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "pixel-unit": "4px",
        "gutter": "24px",
        "container-max-width": "1100px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "pixel": ["'Press Start 2P'", "monospace"],
        "silkscreen": ["'Silkscreen'", "monospace"],
        "vt323": ["'VT323'", "monospace"],
        "display-lg": ["'Press Start 2P'", "monospace"],
        "headline-lg": ["'Press Start 2P'", "monospace"],
        "headline-lg-mobile": ["'Press Start 2P'", "monospace"],
        "label-caps": ["'Silkscreen'", "monospace"],
        "code-sm": ["'JetBrains Mono'", "monospace"],
        "body-md": ["'JetBrains Mono'", "monospace"],
      },
      boxShadow: {
        "pixel": "4px 4px 0px 0px #a900a9",
        "pixel-cyan": "4px 4px 0px 0px #00eefc",
        "pixel-black": "4px 4px 0px 0px #000000",
        "pixel-yellow": "4px 4px 0px 0px #fae500",
        "pixel-lg": "6px 6px 0px 0px #a900a9",
        "pixel-lg-cyan": "6px 6px 0px 0px #00eefc",
      }
    }
  },
  plugins: [],
}
